name: Windows Build

on:
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
  merge_group:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy --workspace --all-targets -- -D warnings
    - name: Test
      run: cargo test --workspace --all-targets
    - name: Build
      run: cargo build --release 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: |
          target/release/halloy.exe
          target/release/halloy.pdb

